# AUTOGENERATED! DO NOT EDIT! File to edit: dev/99_settings.ipynb (unless otherwise specified).

__all__ = ['DATA_DIR', 'DATA_DIR']

# Cell
from path import Path

# Modify these or pass them into the config
DATA_DIR = Path("~/path/to/data_dir").expanduser()
DATA_DIR = Path("~/path/to/frontend_payload_dir").expanduser()
